name: Core C CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - bind-dev
      - v*

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2

    #- name: Setup libfec
    #  run: git clone https://github.com/jgaeddert/libfec.git && cd libfec && ./configure && make && sudo make install

    - name: Setup pybind-dev (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install pybind11-dev

    - name: Setup pybind-dev (macOS)
      if: runner.os == 'macOS'
      run: brew install pybind11

    - name: Setup python dependencies (pip)
      run: sudo -H python3 -m pip install pybind11 numpy matplotlib

    - name: bootstrap
      run: ./bootstrap.sh

    - name: configure
      run: ./configure

    - name: make
      run: make -j 2

    - name: make doc-check
      run: make doc-check

    - name: make check
      run: make -j 2 check
